name: Push Container to Docker Hub and Heroku

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - name: Login Docker Hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: docker build -t exercise3.2 .
      - name: Add tags to image for Docker Hub and Heroku
        run: |
          docker tag exercise3.2 ${{ secrets.DOCKER_USERNAME }}/fr-example
          docker tag exercise3.2 registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fr-example
     